- block:
  - name: install basic packages
    apt: pkg={{ item }} state=present update_cache=true
    with_items:
      - redis-server

  - name: Make sure a service is running
    service:
      state: started
      name: redis
      enabled: yes
  tags: ['redis']
