- block:
  - name: install basic packages
    apt:
      state: present
      update_cache: true
      pkg:
        - redis-server

  - name: Make sure a service is running
    service:
      state: started
      name: redis
      enabled: yes
  tags: ['redis']
