- block:
    - name: install basic packages
      apt:
        state: present
        update_cache: true
        pkg:
          - build-essential
          - git
          - python3-dev
          - python3-venv

    - block:
        - file:
            path: "{{channelstream_rundir}}"
            state: directory
            mode: 0755
        - name: add channelstream config
          template:
            src: config.ini.jinja2
            dest: "{{channelstream_rundir}}/config.ini"
            owner: channelstream
            group: channelstream

        - name: create python venv
          command: "{{channelstream_virtualenv_python}} -m venv {{channelstream_virtualenv_dir}}"

        - name: install channelstream
          pip:
            name: "channelstream=={{channelstream_version}}"
            virtualenv: "{{channelstream_virtualenv_dir}}"
      become_user: channelstream
  tags: ["channelstream"]
