- name: install basic packages
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - build-essential
    - supervisor

- command: apt-get clean

- name: install openjdk-7-jre
  apt: pkg=openjdk-7-jre state=present update_cache=true
  when: ansible_distribution_version|float < 16

- name: install openjdk-8-jre
  apt: pkg=openjdk-8-jre state=present update_cache=true
  when: ansible_distribution_version|float >= 16

- name: add supervisord configs
  template: src=supervisord/appenlight_elasticsearch.jinja2 dest=/etc/supervisor/conf.d/appenlight_elasticsearch.conf owner=root group=root mode=0600

- name: create user appenlight_elasticsearch
  user: name=appenlight_elasticsearch generate_ssh_key=yes ssh_key_bits=2048

- name: check if archive exists
  stat: path=/home/appenlight_elasticsearch/elasticsearch-2.3.1.tar.gz get_checksum=true
  register: sym

- name: grab elasticsearch
  become_user: appenlight_elasticsearch
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.1.tar.gz dest=/home/appenlight_elasticsearch/elasticsearch-2.3.1.tar.gz mode=0660 validate_certs=no
  when: not sym.stat.exists or sym.stat.checksum != '387c5f045843339d486203b0048ff8911e9c8c54'

- name: check if archive exists
  stat: path=/home/appenlight_elasticsearch/elasticsearch-2.3.1.tar.gz get_checksum=true
  register: sym

- name: checking checksum
  fail: msg="Checksum is not correct"
  when: sym.stat.checksum != '387c5f045843339d486203b0048ff8911e9c8c54'

- name: unpack elasticsearch
  become_user: appenlight_elasticsearch
  unarchive: src=/home/appenlight_elasticsearch/elasticsearch-2.3.1.tar.gz dest=/home/appenlight_elasticsearch/ copy=no

- name: ensure no es present form previous steps
  file: path=/home/appenlight_elasticsearch/elasticsearch state=absent

- name: mv elasticsearch
  become_user: appenlight_elasticsearch
  command: mv "/home/appenlight_elasticsearch/elasticsearch-2.3.1" /home/appenlight_elasticsearch/elasticsearch

- name: add elasticsearch config
  become_user: appenlight_elasticsearch
  copy: src=elasticsearch.yml dest=/home/appenlight_elasticsearch/elasticsearch/config/ owner=appenlight_elasticsearch group=appenlight_elasticsearch mode=0644

- name: install elasticsearch delete-by-query plugin
  become_user: appenlight_elasticsearch
  command: /home/appenlight_elasticsearch/elasticsearch/bin/plugin install delete-by-query
