- name: install basics
  apt: pkg={{ item }} state=present
  with_items:
  - sshpass
  - build-essential
  - vim
  - mc
  - curl
  - acl
  - update-motd
  - update-notifier-common
  - landscape-common
  register: error_handler
  until: error_handler|success
  retries: 99
  delay: 15

- command: apt-get clean

- name: add pam limits to common session
  lineinfile: dest=/etc/pam.d/common-session state=present line="session required pam_limits.so" insertafter=EOF

- name: customize the server sysctl vm.swappiness
  lineinfile: dest=/etc/sysctl.conf state=present line="vm.swappiness = 1" insertafter=EOF

- name: customize the server sysctl vm.max_map_count
  lineinfile: dest=/etc/sysctl.conf state=present line="vm.max_map_count = 262144" insertafter=EOF

- name: customize the server sysctl vm.overcommit_memory
  lineinfile: dest=/etc/sysctl.conf state=present line="vm.overcommit_memory = 1" insertafter=EOF

- name: update limits
  copy: src=security/limits.d/root.conf dest=/etc/security/limits.d/root.conf

- name: update sysctl
  command: sysctl -p

- name: install fail2ban
  apt: pkg=fail2ban state=present

- name: fail2ban whitelist
  replace: dest=/etc/fail2ban/jail.conf regexp="^ignoreip =.*"  replace="ignoreip = 127.0.0.1 {{ fail2ban_whitelist }}"

- name: fail2ban bantime
  replace: dest=/etc/fail2ban/jail.conf regexp="^bantime  =.*"  replace="bantime  = {{ fail2ban_bantime }}"

- name: disable root ssh login
  replace: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin .*"  replace="PermitRootLogin no"

- name: set ssh port
  replace: dest=/etc/ssh/sshd_config regexp="^Port .*"  replace="Port {{custom_ssh_port}}"

- name: turn on security updates
  command: env DEBIAN_FRONTEND=noninteractive dpkg-reconfigure --priority=low unattended-upgrades
