- name: install mysql server
  apt: pkg=mysql-server state=present
  register: error_handler
  until: error_handler|success
  retries: 99
  delay: 15

- command: apt-get clean

- name: customize the serveer
  template: src=customized.jinja2 dest=/etc/mysql/conf.d/customized.cnf
