  - name: install libvirt if missing
    apt:
      state: present
      pkg:
        - qemu-kvm
        - libvirt-bin
        - bridge-utils
  register: error_handler
  until: error_handler is success
  retries: 99
  delay: 15
  tags: ["kvm"]
