---
- hosts: "{{hosts}}"
  become: true
  vars:
    hostname: appenlight.local
    ansible_ssh_pipelining: true
    elasticsearch_ram: 1024m
    nginx_default_listen: 80
    nginx_user: www-data
    appenlight_domain: appenlight_dev
    postfix_fqdn: "{{appenlight_domain}}"
    custom_ssh_port: 9022
    appenlight_admin_password: admin #so we can gen password when invoking VM
    appenlight_pg_password: test #so we can gen password when invoking VM
    users_accounts:
      - user: appenlight
      - user: channelstream
    postgresql_users:
      - name: appenlight
        password: "{{appenlight_pg_password}}"
    postgresql_databases:
        - name: appenlight
          owner: appenlight
    nginx_certificates_self_signed:
        - "{{appenlight_domain}}"
    nginx_vhost_simple_vhost_dir: "files/appenlight.prod/vhosts/*"
    appenlight_repo_branch: 2.0.0rc1
    appenlight_uptime_repo_branch: 2.0.0rc1
  roles:
    - role: basic
    - role: users
    - role: nodejs
    - role: postgresql
    - role: postfix
    - role: nginx
    - role: nginx_certificates
    - role: nginx_vhost_simple
    - role: redis
    - role: elasticsearch
    - role: channelstream
    - role: channelstream_init
    - role: appenlight
    - role: appenlight_init
    - role: hostname
