- name: install pycurl if missing
  apt: pkg=python-pycurl state=present
  register: error_handler
  until: error_handler|success
  retries: 99
  delay: 15

- name: add nginx repo
  apt_repository: repo="deb http://nginx.org/packages/mainline/ubuntu/ {{ansible_distribution_release}} nginx" state=present update_cache=true

- name: install latest nginx
  apt: pkg=nginx state=present force=yes

- command: apt-get clean

- name: create keys dir
  file: path=/etc/nginx/keys state=directory mode=0700

- name: create dhparam
  command: openssl dhparam -out /etc/nginx/keys/dhparam.pem 2048 creates=/etc/nginx/keys/dhparam.pem

- name: create default site self-signed cert
  command: openssl req -x509 -nodes -days 7300 -newkey rsa:2048 -keyout /etc/nginx/keys/default_cert.key -out /etc/nginx/keys/default_cert.crt -subj "/C=PL/ST=Poland/L=Warsaw/O=Webreactor/OU=SpecOPS/CN=default.com" creates=/etc/nginx/keys/default_cert.crt

- name: create self signed domain certs
  command: openssl req -x509 -nodes -days 7300 -newkey rsa:2048 -keyout /etc/nginx/keys/{{item}}.key -out /etc/nginx/keys/{{item}}.crt -subj "/C=PL/ST=Germany/L=Berlin/O=Unknown/OU=SpecOPS/CN={{item}}" creates=/etc/nginx/keys/{{item}}.crt
  with_items: "{{nginx_self_signed_domains}}"

- name: set dhparam permissions
  file: path=/etc/nginx/keys/dhparam.pem mode=0600

- name: template default config
  template: src=nginx.conf.jinja2 dest=/etc/nginx/nginx.conf

- name: customize the server
  copy: src=nginx/customized.conf dest=/etc/nginx/conf.d/customized.conf

- name: create new default html dir
  file: path=/var/www/default/ state=directory

- name: ensure letsencrypt exists
  file: path=/usr/share/nginx/letsencrypt mode=0751 state=directory

- file: path=/usr/share/nginx/letsencrypt/.well-known mode=0751 state=directory

- name: copy new default html
  copy: src=nginx/index.html dest=/var/www/default/index.html

- name: ensure sites-available exists
  file: path=/etc/nginx/sites-available mode=0750 state=directory

- name: ensure sites-enabled exists
  file: path=/etc/nginx/sites-enabled mode=0750 state=directory

- name: delete old default site
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: delete old default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: create new default
  copy: src=nginx/default dest=/etc/nginx/sites-available/default

- name: install SSL certs
  copy: src={{ item.src }} dest=/etc/nginx/keys/{{ item.dest_name }}
  with_items: "{{nginx_ssl_certs}}"
  when: nginx_ssl_certs is defined

- name: set cert permissions
  file: path=/etc/nginx/keys/{{ item.dest_name }} mode=0600
  with_items: "{{nginx_ssl_certs}}"
  when: nginx_ssl_certs is defined

- name: create nginx vhosts
  template: src=nginx-vhost.jinja2 dest=/etc/nginx/sites-available/{{ item.name }}.conf
  with_items: "{{nginx_vhosts}}"

- name: enable nginx vhosts
  file: src=/etc/nginx/sites-available/{{ item.name }}.conf dest=/etc/nginx/sites-enabled/{{ item.name }}.conf state=link
  with_items: "{{nginx_vhosts}}"

- name: test nginx
  shell: nginx -t
