- name: install basic packages
  apt: pkg=pure-ftpd state=present
  register: error_handler
  until: error_handler|success
  retries: 99
  delay: 15

- command: apt-get clean

- name: work only on tls
  lineinfile: dest=/etc/pure-ftpd/conf/TLS line="2" create="yes"

- name: Chroot everyone
  lineinfile: dest=/etc/pure-ftpd/conf/ChrootEveryone line="yes" create="yes"

- name: disable PAMAuthentication
  lineinfile: dest=/etc/pure-ftpd/conf/PAMAuthentication line="no" create="yes"

- name: disable UnixAuthentication
  lineinfile: dest=/etc/pure-ftpd/conf/UnixAuthentication line="no" create="yes"

- name: disable anonymous
  lineinfile: dest=/etc/pure-ftpd/conf/NoAnonymous line="yes" create="yes"

- name: minimum user id
  lineinfile: dest=/etc/pure-ftpd/conf/MinUID line="1000" create="yes"

- name: enable passive transfers
  lineinfile: dest=/etc/pure-ftpd/conf/PassivePortRange line="50000 50120" create="yes"

- name: generate ssl key
  shell: openssl req -x509 -nodes -days 7300 -newkey rsa:2048 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem -subj "/C=PL/ST=Poland/L=Warsaw/O=Webreactor/OU=SpecOPS/CN=default.com" creates=/etc/ssl/private/pure-ftpd.pem

- name: set permissions on the key
  file: path=/etc/ssl/private/pure-ftpd.pem mode=0600
